version: '3.7'
services:
  db:
    platform: linux/x86_64 # workaround for mac M1 chips
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3306:3306
    command: --default-authentication-plugin=mysql_native_password

  db-setup:
    platform: linux/x86_64 # workaround for mac M1 chips
    image: mysql:5.7
    depends_on:
      - db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: root
      MYSQL_PWD: password
    links:
      - db:mysqldb
    entrypoint: ["/bin/bash", "-c"]
    command:
      - |
        while true; do
            mysql -hmysqldb -u$$MYSQL_USER -p$$MYSQL_ROOT_PASSWORD mysql -e 'show tables;' >/dev/null 2>&1
            if [ $$? -eq 0 ]; then
                break
            fi
            echo "Waiting for db..."
            sleep 5
        done
        
        echo "Initializing db..."
        mysql -hmysqldb -u$$MYSQL_USER -p$$MYSQL_ROOT_PASSWORD mysql <<'EOF'
        CREATE DATABASE IF NOT EXISTS dev_posts;

        CREATE USER IF NOT EXISTS 'username'@'%' IDENTIFIED BY 'password';
        GRANT ALL PRIVILEGES ON *.* TO 'username'@'%';
        EOF
        
        echo "Done! list of users:"
        mysql -hmysqldb -u$$MYSQL_USER -p$$MYSQL_ROOT_PASSWORD mysql -e "select User from mysql.user;"

  users-api:
    build:
      context: ./user-mgmt/
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - db-setup
    environment:
      MYSQL_HOST: db
      FILE_SERVING_URL: http://dummy-pdf-or-png:3000
    ports:
      - "8080:8080"

  dummy-pdf-or-png:
    build:
      context: ./dummy-pdf-or-png/
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "3000:3000"