appname: user-mgmt-app
replicaCount: 2
image:
  repository: pedropeixoto6/user-mgmt-api
  tag: 3c4faa9bac25fea323d8eeef2e716727a0d2da3b
  pullPolicy: IfNotPresent
service:
  name: user-mgmt-service
  type: ClusterIP
  port:
    name: rest
    protocol: TCP
    externalPort: 8080
    internalPort: 8080
mysql:
  host: mysql-prod
  db: prod_users
files:
  servingUrl: http://dummy-pdf-or-png-service:3000