appname: user-mgmt-app
replicaCount: 2
image:
  repository: pedropeixoto6/user-mgmt-api
  tag: a8ef2d024b4bec9a3c4317075ccad0004684c334
  pullPolicy: IfNotPresent
service:
  name: user-mgmt-service
  type: ClusterIP
  port:
    name: rest
    protocol: TCP
    externalPort: 8080
    internalPort: 8080
mysql:
  host: mysql-prod
  db: prod_users
files:
  servingUrl: http://dummy-pdf-or-png-service:3000