appname: user-mgmt-app
replicaCount: 2
image:
  repository: pedropeixoto6/user-mgmt-api
  tag: 3b49f736ca924d29821bf2f5bf708192285ce41e
  pullPolicy: IfNotPresent
service:
  name: user-mgmt-service
  type: ClusterIP
  port:
    name: rest
    protocol: TCP
    externalPort: 8080
    internalPort: 8080
mysql:
  host: mysql-prod
  db: prod_users
files:
  servingUrl: http://dummy-pdf-or-png-service:3000