appname: dummy-pdf-or-png-service-app
replicaCount: 2
image:
  repository: pedropeixoto6/dummy-pdf-or-png-api
  tag: 539330c4771f412e5bb8b836030d8201d11daa70
  pullPolicy: IfNotPresent
service:
  name: dummy-pdf-or-png-service
  type: ClusterIP
  port:
    name: rest
    protocol: TCP
    externalPort: 3000
    internalPort: 3000