apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgresql-prod
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: prod
  project: default
  source:
    chart: mysql
    helm:
      values: |
        architecture: standalone
        image:
          tag: 5.7
        auth:
          rootPassword: "password"
          createDatabase: true
          database: "prod_users"
          username: "username"
          password: "password"
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 9.10.4
  syncPolicy:
    automated:
      prune: true
      selfHeal: true