apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: prod
  project: default
  source:
    path: infra/terraform/services/argocd/apps/
    repoURL: https://github.com/pedromspeixoto/k8s-user-mgmt.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true